# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"\x1e\n\x0bTestRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x1f\n\x0cTestResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2G\n\x0bTestService\x12\x38\n\x0fsendTestMessage\x12\x11.test.TestRequest\x1a\x12.test.TestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTREQUEST']._serialized_start=20
  _globals['_TESTREQUEST']._serialized_end=50
  _globals['_TESTRESPONSE']._serialized_start=52
  _globals['_TESTRESPONSE']._serialized_end=83
  _globals['_TESTSERVICE']._serialized_start=85
  _globals['_TESTSERVICE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
